### ISSUE TITLE
21:9

### ISSUE THREAD

**Issue by d4kir92** [mayope/raids-issues#1]
**Describe the bug**
i cant set my resolution to a 21:9 one

**To Reproduce**
start game with 21:9 monitor

**Expected behavior**
working 21:9

**Desktop (please complete the following information):**
Win11

**Comment by klg71** [comment]
Hey @d4kir92 thanks for opening this issue :) I will have a look into it.

**Comment by klg71** [comment]
That is a relict from the youtube trailer :) But I will remove it now.

**Comment by klg71** [comment]
I tried it with 21:9 in the Unity-Editor but I can't find the error. Could you provide a Screenshot of your problem? Sadly I don't have a 21:9 monitor available right now.

**Comment by d4kir92** [comment]
![image](https://github.com/mayope/raids-issues/assets/23246564/fc331d81-30bf-4c8e-8d99-64c3d38b3519)

![image](https://github.com/mayope/raids-issues/assets/23246564/e3cdec14-2a47-4bbd-9d38-12ed51683806)

**Comment by klg71** [comment]
Hey @d4kir92 could you try Settings->Interface-> Reset UI.
I am having some trouble reproducing your issue :/
Could you tell me the absolute pixel size of your monitor? I have tested it with 2560x1080 and that seems to work...

**Comment by d4kir92** [comment]
![image](https://github.com/mayope/raids-issues/assets/23246564/0993b8a5-817f-4cda-a6a5-674cb7552041)
![image](https://github.com/mayope/raids-issues/assets/23246564/9c708863-3112-432b-a919-fff0162d9cc1)

2560x1080
other unity game (Tiny Tactics) also had this problem and didnt found a fix, maybe an unity problem
but rust for example can do 21:9 which is also unity game

when i do ALT+ENTER 2 times
![image](https://github.com/mayope/raids-issues/assets/23246564/2486da96-bb07-473e-b0c8-b30a1b4384fc)
this trick works, BUT some things are cut off
![image](https://github.com/mayope/raids-issues/assets/23246564/329504fd-79a3-4949-8c44-184bb35113aa)

![image](https://github.com/mayope/raids-issues/assets/23246564/1239e0ac-7b08-40ea-9ea1-304fd376e12b)

**Comment by d4kir92** [comment]
this may result into not playable when for example the login is out of the window :P

**Comment by klg71** [comment]
Thanks for the testing :) I am currently working on the cut-off. I guess I can release it with the next release.

**Comment by d4kir92** [comment]
maybe newly installed dont need to press Alt+Enter 2 times

**Comment by d4kir92** [comment]
![image](https://github.com/mayope/raids-issues/assets/23246564/f2b39e48-f30f-4938-8349-78b9b27d370d)

nameplate of my own player?
![image](https://github.com/mayope/raids-issues/assets/23246564/37667524-87b5-4114-a440-97fc0ac3cd66)
