### ISSUE TITLE
Cannot move, do actions, enter raids, nearly anything in main server.

### ISSUE THREAD

**Issue by Dankoro21** [mayope/raids-issues#13]
**Describe the bug**

After breaking a raid (see below) I cannot move, do actions, target things, or enter new raids. I can go into the tutorial but cannot do anything. I tried logging out and back in and reinstalling, but still can't. I even waited a day, thinking it will just fix overnight (server reset or something) but I still cannot move on main server. I can move and do almost everything on the Beta server (I keep getting kicked out of the first raid half-way through the elephant boss), it's only the main server I cannot do anything.

**To Reproduce**
1. Go to 'Raid: Sludge Madness'
2. Max out number of raider bots to 14+Player (any class combo really, I broke after one try, I did have a few spear users) and enter the raid. 
3. Gather up all of the slimes in the first room to AOE down together.
4. No error code, everything just...stopped and I'm permanently like this.

**Expected behavior**

I expected to be able to gather all of the slimes up to AOE them down with a full raid to see how efficient it would be. Thought it would go smoothly, though I think it overloaded something on my client side that won't fix.

**Screenshots**
If applicable, add screenshots to help explain your problem. (
![20231009215419_1](https://github.com/mayope/raids-issues/assets/147464339/4308d69d-2f65-4052-b7ea-b0271e6f5902)
I don't know quite how to show anything outside of when changing loadouts all abilities go on a permanent 20sec cooldown.

**Log Files**
Please attach both `Player.log` and `Player-prev.log` located in `C:\Users\<username>\AppData\LocalLow\Mayope Software Services UG(haftungsbeschränkt)\RaidsClient`
(they dropped in the below section)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Win 10
 - Browser [e.g. chrome, safari] Chrome (not sure if applicable?)
 - Version [e.g. 22]: I don't see a version #, so as of 10/9/2023

[Player.log](https://github.com/mayope/raids-issues/files/12852554/Player.log)
[Player-prev.log](https://github.com/mayope/raids-issues/files/12852555/Player-prev.log)

**Additional context**
Add any other context about the problem here. I've said about as much as I can.

**Comment by klg71** [comment]
Hey @Dankoro21 I restarted the server and it should work again. I will investigate the server error :)

**Comment by klg71** [comment]
Please reopen if the bug appears again :)
