### ISSUE TITLE
Duplicated key binds

### ISSUE THREAD

**Issue by hboelke** [mayope/raids-issues#3]
**Describe the bug**

It's possible to use the same key multiple times.

**To Reproduce**
1. Go to Settings -> Controls
2. Set your keybinds with same key multiple times

**Expected behavior**

You shouldn't be able to set the same key mutiple times

**Screenshots**

![Screenshot](https://cdn.discordapp.com/attachments/850802796764463197/1146906713908318420/image.png)

**Comment by klg71** [comment]
Hey @hboelke thanks for opening this issue :) I will implement it soon.

**Comment by klg71** [comment]
Released on Steam with latest Build.
