### ISSUE TITLE
Audio Adjustment doesn't have a working slider

### ISSUE THREAD

**Issue by umassfan29** [mayope/raids-issues#5]
**Describe the bug**
When going to the sound settings the slider is missing to be able to adjust the sounds in the game

**To Reproduce**
1. Go to Settings
2. Click on 'Audio"
4. See that the 3 sound settings don't have a slider associated with them

**Expected behavior**
Expected to have a slider to adjust the sound

**Screenshots**
![image](https://github.com/mayope/raids-issues/assets/62523501/e8b94afc-7b26-4cfd-b999-050b4388c517)

**Log Files**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by klg71** [comment]
Should be fixed in the current "beta" branch on Steam.

**Comment by umassfan29** [comment]
It still seems buggy.  I am able to move the sliders now but look what happens.

I first want to change the effects slider to half:

![image](https://github.com/mayope/raids-issues/assets/62523501/cd56b98b-3df4-4cbe-b833-b94515e91133)

Then it doesn't make any sound anymore because when I go back into the settings menu the two sliders I adjusted are turned down all the way

![image](https://github.com/mayope/raids-issues/assets/62523501/334fe2db-0177-4b49-b8c4-5cacc13aed6f)

**Comment by umassfan29** [comment]
fixed!
