### ISSUE TITLE
Summon Fire Elemental has 30 sec CD if you move while casting

### ISSUE THREAD

**Issue by umassfan29** [mayope/raids-issues#6]
**Describe the bug**
When I accidentally move while casting Summon Fire elemental the ability goes on a 30 second long CD.

**To Reproduce**
1. Cast Summon Fire Elemental
2. Move forward during the cast
3. Notice how Cooldown is 30 seconds like I casted it

**Expected behavior**
There could be an argument for a 1 or 2 second penalty for interrupting a cast but I feel like waiting the entire cooldown again to re use is a bug

**Screenshots**

**Log Files**

**Desktop (please complete the following information):**

**Additional context**

**Comment by klg71** [comment]
Hey @umassfan29 thanks for finding this bug :) I will take steps to prevent it from happening.

**Comment by klg71** [comment]
Should be fixed in the current Steam "beta" branch using the Beta Gameserver

**Comment by umassfan29** [comment]
This is confirmed to be fixed when on the beta branch
