### ISSUE TITLE
Pillar of Flame AOE Damage ring doesn't show in Sludge madness

### ISSUE THREAD

**Issue by umassfan29** [mayope/raids-issues#8]
**Describe the bug**
Pillar of Flame AOE Damage ring doesn't show in Sludge madness during or after the cast

**To Reproduce**
1. Go to Sludge Madness
2. Cast Pillar of Flame
3. See that there is no aoe damage ring showing on floor

**Expected behavior**
A damage ring should be on the floor like other raids.  Below is me mid cast with it not showing up where i casted it in front of me

**Screenshots**
![image](https://github.com/mayope/raids-issues/assets/62523501/cfc674ee-e7a6-4a3a-97ea-6aab2d742fa8)

**Log Files**
Please attach both `Player.log` and `Player-prev.log` located in `C:\Users\<username>\AppData\LocalLow\Mayope Software Services UG(haftungsbeschränkt)\RaidsClient`

**Desktop (please complete the following information):**

**Additional context**

**Comment by klg71** [comment]
Should be fixed on the "beta" - Branch :)

**Comment by umassfan29** [comment]
@klg71 I still am not seeing it during my cast on the beta branch.  See below.  I casted it where my mouse cursor is

![image](https://github.com/mayope/raids-issues/assets/62523501/7363d2c8-8ee1-4644-869f-8e02fdf1ffde)

**Comment by klg71** [comment]
Ok fixed it again. Hope it does work for you now: 
![Screenshot 2023-10-03 145320](https://github.com/mayope/raids-issues/assets/7859791/688174e7-da1e-4e3e-bcc1-9d2b846d48cd)

**Comment by umassfan29** [comment]
tested on latest beta branch and works!
